# Generated by Django 3.0.3 on 2020-05-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latinoMusic_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file_uploaded',
            name='file_name',
        ),
        migrations.AddField(
            model_name='file_uploaded',
            name='track',
            field=models.FileField(blank=True, upload_to='audio/'),
        ),
        migrations.AddField(
            model_name='file_uploaded',
            name='track_title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
