# Generated by Django 3.0.3 on 2020-05-16 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('latinoMusic_app', '0004_subscribers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=120)),
                ('genre_image', models.ImageField(blank=True, upload_to='profile_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Processed_payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=60)),
                ('paid', models.BooleanField(default=False)),
                ('total_paid', models.FloatField()),
                ('date', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('track', models.FileField(blank=True, upload_to='audio/')),
                ('year', models.PositiveIntegerField()),
                ('duration', models.DurationField()),
                ('genreid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='latinoMusic_app.Genre')),
            ],
        ),
        migrations.RenameModel(
            old_name='Artists',
            new_name='Artist',
        ),
        migrations.RemoveField(
            model_name='processed_payments',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='songs',
            name='genreid',
        ),
        migrations.RenameModel(
            old_name='SongPlays',
            new_name='SongPlay',
        ),
        migrations.DeleteModel(
            name='Genres',
        ),
        migrations.DeleteModel(
            name='Processed_payments',
        ),
        migrations.DeleteModel(
            name='Songs',
        ),
        migrations.AlterField(
            model_name='songplay',
            name='song_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='latinoMusic_app.Song'),
        ),
    ]
