# Generated by Django 3.0.3 on 2020-05-18 19:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('latinoMusic_app', '0005_auto_20200516_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processed_payment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='songplay',
            old_name='song_id',
            new_name='songid',
        ),
        migrations.RenameField(
            model_name='songplay',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='genre',
            name='genre_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='latinoMusic_app.Artist'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='year',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='songplay',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Trending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='latinoMusic_app.Song')),
            ],
        ),
    ]
