# Generated by Django 3.0.3 on 2020-05-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latinoMusic_app', '0006_auto_20200518_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist_image',
            field=models.ImageField(blank=True, null=True, upload_to='artists_rep'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_image',
            field=models.ImageField(blank=True, upload_to='artists_rep'),
        ),
        migrations.AlterField(
            model_name='song',
            name='track',
            field=models.FileField(blank=True, upload_to='audio'),
        ),
    ]
