# Generated by Django 3.0.3 on 2020-05-24 08:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('latinoMusic_app', '0009_auto_20200523_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='year',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
