# Generated by Django 3.0.3 on 2020-05-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latinoMusic_app', '0011_profile_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('occupation', models.CharField(blank=True, max_length=60)),
                ('profile_pic', models.ImageField(blank=True, upload_to='testimonials')),
                ('comment', models.TextField()),
            ],
        ),
    ]
